### ISSUE TITLE
how to download macos binary

### ISSUE THREAD

**Issue by drkamarul** [MangoTheCat/blog_installing_packages#2]
Wonderful codes. Can you show us how to download packages for MacOS binary? the codes below does not work

```pkgInfo2 <- download.packages(pkgs = packages, destdir = getwd(), type = "mac.binary")```

Which returns these error messages

```cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/3.4/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/3.4/PACKAGES.gz': HTTP status was '404 Not Found'cannot open URL ... ```

**Comment by grahamrp** [comment]
Sure, you need to use `type = "mac.binary.el-capitan"` instead of "mac.binary". This is because since R 3.4.0, CRAN only provides binaries for MacOS El Capitan and higher.

Glad you find it useful!
