### ISSUE TITLE
Binary for MacOS

### ISSUE THREAD

**Issue by drkamarul** [MangoTheCat/blog_installing_packages#3]
Very useful functions. May I know how to download packages for MacOS?

I wrote the codes below, but they did not work

 ```pkgInfo <- download.packages(pkgs = packages, destdir = getwd(), type = "mac.binary")```

These the error messages I received 

```cannot open URL 'https://cran.csiro.au/bin/macosx/contrib/3.4/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://cran.csiro.au/bin/macosx/contrib/3.4/PACKAGES.gz': HTTP status was '404 Not Found'cannot open URL 'https://cran.csiro.au/bin/macosx/contrib/3.4/PACKAGES': HTTP status was '404 Not Found'unable to access index for repository https://cran.csiro.au/bin/macosx/contrib/3.4: ...```

**Comment by grahamrp** [comment]
@drkamarul Did you see I closed the issue you raised yesterday with an answer? Take a look at the original issue you raised: #2

**Comment by drkamarul** [comment]
Yes you did. It seems that have overlooked that. My apology for any inconveniences. I will close the issue. Many thanks again.
