### ISSUE TITLE
Can I specify the R version for downloading the corresponding packages?

### ISSUE THREAD

**Issue by McCompexpert** [MangoTheCat/blog_installing_packages#4]
My working environment with Internet connection has R 3.3.1.
The new PC without internet access has the newer version of R 3.5.0

When I am runing your functions on the PC with the older R, then I get all the libraries downloaded from CRAN https://cran.rstudio.com/bin/windows/contrib/3.3

Installing them on the PC with 3.5.0 is causing problems

**Comment by grahamrp** [comment]
Interesting use case. The argument that controls which R version gets downloaded is the `contriburl` argument to `download.packages`, which defaults to figuring out the R version of the current machine. To download packages for a different R version you could override the default like this:
```
# Get exisiting contrib url(s)
contribUrlNew <- contrib.url(getOption("repos"), "win.binary")
# Modify the R version
contribUrlNew <- sub("3.3", "3.5", contribUrlNew)
# Call download.packages with the modified contribUrl
download.packages(pkgs = packages, destdir = getwd(), type = "win.binary",
                  contriburl = contribUrlNew)
```

**Comment by McCompexpert** [comment]
Yep, exactly that what I needed, thank you very much!
