### ISSUE TITLE
Doesn't download package dependencies

### ISSUE THREAD

**Issue by Dr-Vikash** [MangoTheCat/blog_installing_packages#5]
I tried downloading plotrix and data.table packages with your code as follows:

I ran the following code in a script titled "to_know_package_dependencies.R":
getDependencies <- function(packs){
dependencyNames <- unlist(
tools::package_dependencies(packages = packs, db = available.packages(),
which = c("Depends", "Imports"),
recursive = TRUE))
packageNames <- union(packs, dependencyNames)
packageNames
}
packages <- getDependencies(c("plotrix", "data.table"))

On a second script, I ran following code in a script titled "to_download_package.R"
setwd("G:/r studio files/offline package for/")
pkgInfo <- download.packages(pkgs = packages, destdir = getwd(), type = "win.binary")
write.csv(file = "pkgFilenames.csv", basename(pkgInfo[, 2]), row.names = FALSE)
After running the second script I was able to download the main packages "plotrix" and "data.table". However, other dependent packages could not be downloaded and i got following messages on console:
source('G:/r studio files/offline package for/to_download_package.R')
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/plotrix_3.7-2.zip'
Content type 'application/zip' length 1053607 bytes (1.0 MB)
downloaded 1.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/data.table_1.11.4.zip'
Content type 'application/zip' length 1829595 bytes (1.7 MB)
downloaded 1.7 MB

Warning in download.packages(pkgs = packages, destdir = getwd(), type = "win.binary") :
no package ‘grDevices’ at the repositories
Warning in download.packages(pkgs = packages, destdir = getwd(), type = "win.binary") :
no package ‘graphics’ at the repositories
Warning in download.packages(pkgs = packages, destdir = getwd(), type = "win.binary") :
no package ‘stats’ at the repositories
Warning in download.packages(pkgs = packages, destdir = getwd(), type = "win.binary") :
no package ‘utils’ at the repositories
Warning in download.packages(pkgs = packages, destdir = getwd(), type = "win.binary") :
no package ‘methods’ at the repositories

where we had following info in packages character vector
[1] "plotrix" "data.table" "grDevices" "graphics" "stats" "utils" "methods"

Please help. Thank you

**Comment by adfi** [comment]
Hi @Dr-Vikash, thank you for your question.  The packages that plotrix and data.table depend on are all part of the core R library. These packages are installed together with R so do not require separate installation.  So in this instance you can safely ignore the warnings. 

I will see if there is a way to filter out these packages and let you know.

**Comment by Dr-Vikash** [comment]
Thank you sir for your quick response. Much appreciated.
Regards
Vikash
